# Generated by Django 4.2.27 on 2026-01-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IPI Group', max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('fiscal_year_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('share_certificate_number', models.CharField(blank=True, max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shareholders/photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='shareholders.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shareholders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shareholder',
                'verbose_name_plural': 'Shareholders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Share Issue'), ('PURCHASE', 'Share Purchase'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('BONUS', 'Bonus Issue'), ('RIGHTS', 'Rights Issue'), ('BUYBACK', 'Share Buyback'), ('CONVERSION', 'Conversion'), ('ADJUSTMENT', 'Adjustment'), ('DIVIDEND', 'Dividend'), ('SPLIT', 'Stock Split'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=20)),
                ('shares', models.DecimalField(decimal_places=2, help_text='Number of shares involved in the transaction', max_digits=20)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=4, help_text='Price per share at the time of transaction', max_digits=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total transaction amount (shares * price_per_share)', max_digits=20, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, help_text='Effective date of the transaction')),
                ('entry_date', models.DateTimeField(auto_now_add=True, help_text='When this transaction was recorded')),
                ('approval_date', models.DateTimeField(blank=True, help_text='When this transaction was approved', null=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='When this transaction was completed', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number or identifier', max_length=100)),
                ('certificate_number', models.CharField(blank=True, help_text='Share certificate number if applicable', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, help_text='Any supporting document for this transaction', null=True, upload_to='transactions/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shareholders.shareholder')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, help_text='Effective date of the transfer')),
                ('shares', models.DecimalField(decimal_places=2, help_text='Number of shares to transfer', max_digits=20)),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=4, help_text='Price per share for this transfer (if applicable)', max_digits=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total transfer amount (shares * price_per_share)', max_digits=20, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number or identifier', max_length=100)),
                ('certificate_number', models.CharField(blank=True, help_text='New share certificate number if applicable', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True, help_text='Terms and conditions of the transfer')),
                ('attachment', models.FileField(blank=True, help_text='Any supporting document for this transfer', null=True, upload_to='transfers/attachments/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_transfers', to='shareholders.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_shareholder', models.ForeignKey(help_text='Shareholder transferring the shares', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='shareholders.shareholder')),
                ('to_shareholder', models.ForeignKey(help_text='Shareholder receiving the shares', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='shareholders.shareholder')),
            ],
            options={
                'verbose_name': 'Share Transfer',
                'verbose_name_plural': 'Share Transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('director_type', models.CharField(choices=[('EXECUTIVE', 'Executive Director'), ('NON_EXECUTIVE', 'Non-Executive Director'), ('INDEPENDENT', 'Independent Director'), ('CHAIRPERSON', 'Chairperson'), ('MANAGING', 'Managing Director'), ('ALTERNATE', 'Alternate Director')], default='EXECUTIVE', max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('appointed_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('biography', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='shareholders.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'ordering': ['-is_active', 'director_type', 'full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name',), name='single_company_constraint'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='shareholder_transac_4560b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='shareholder_status_160659_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='shareholder_transac_6c9ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['shareholder'], name='shareholder_shareho_0fdb38_idx'),
        ),
        migrations.AddIndex(
            model_name='sharetransfer',
            index=models.Index(fields=['transfer_date'], name='shareholder_transfe_e31457_idx'),
        ),
        migrations.AddIndex(
            model_name='sharetransfer',
            index=models.Index(fields=['status'], name='shareholder_status_9040fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sharetransfer',
            index=models.Index(fields=['from_shareholder'], name='shareholder_from_sh_b6ec7f_idx'),
        ),
        migrations.AddIndex(
            model_name='sharetransfer',
            index=models.Index(fields=['to_shareholder'], name='shareholder_to_shar_eb9a06_idx'),
        ),
        migrations.AddIndex(
            model_name='sharetransfer',
            index=models.Index(fields=['company'], name='shareholder_company_e90cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='shareholder',
            index=models.Index(fields=['id_number'], name='shareholder_id_numb_adcd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='shareholder',
            index=models.Index(fields=['full_name'], name='shareholder_full_na_b66421_idx'),
        ),
        migrations.AddIndex(
            model_name='shareholder',
            index=models.Index(fields=['is_active'], name='shareholder_is_acti_5d7f0e_idx'),
        ),
    ]
