# Generated by Django 4.2.27 on 2026-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], help_text='Gender of the director', max_length=1),
        ),
    ]
